// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "MapServiceHandler.h"
#include <stdio.h>

#ifndef DAsyncMapCli
#include <stdint.h>
extern uint64_t g_total_recv; 
extern void StatisHandle();

MapServiceHandler::MapServiceHandler()
{
    // Your initialization goes here
}


void MapServiceHandler::compute(ComputeResp& _return, const ComputeReq& req) 
{
    __sync_fetch_and_add(&g_total_recv, 1);
    StatisHandle();

    #ifdef PRINT
    fprintf(stdout, 
            "req.cityId=%d\t"
            "creq.oidList.size=%ld\t"
            "creq.didList.size=%ld\n", 
            req.cityId, 
            req.oidList.size(), 
            req.didList.size()); 
    #endif

    _return.type = OrderType::COMMONORDER;
    _return.data = std::string("hello client");
    return;
}

#endif //#ifndef DAsyncMapCli

